### ISSUE TITLE
Menanyakan konflict #05 Method

### ISSUE THREAD

**Issue by MuhamadIkhsanKamal** [FT3006-OOP/OOP-TI3E#248]
Assalamualaikum warahmatullahi wabarakatuh

pa permasalahan #05 Method punya saya belum selesai . saya mencoba beberapa cara termasuk menghapus commit yang waktu itu banyak seklai. alhamduillah commitnya bisa dihapus. saya buat ulang lagu projectnya pa. tapi setelah di git push, projectnya malah ngelink kepada project yang pertama saya dibuat ditanggal 26 oktober pa. jadi pas di pull & request masih tetap terjadi konflict.

bagaimana kelanjutan project saya ? apakah saya harus buat direktori baru khusus project saya tentang method ? 

mohon bimbingannya pak 

wassalamualaikum warahmatullahi wabarakatuh

**Comment by autobot-byte** [comment]
Walaikumsalam..

@MuhamadIkhsanKamal 

Ikuti langkah2 berikut untuk memperbaiki "Konflik" 

**Langkah 1: Dari repositori proyek Anda, periksa cabang baru dan uji perubahannya.**

```
git checkout -b MuhamadIkhsanKamal-master master
git pull git://github.com/MuhamadIkhsanKamal/OOP-TI3E.git master
```

**Langkah 2: Gabungkan perubahan dan perbarui di GitHub.**

```
git checkout master
git merge --no-ff MuhamadIkhsanKamal-master
git push origin master
```
